on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC 20:00 -> CST (China) 4:00, see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '0 1 * * *'

name: Gitee
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Mirror Github to Gitee with white list
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/mumuba2020
        dst: gitee/mumuba2020
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        static_list: 'sync'
        force_update: true
        debug: true
